/* MADHYUM WEBSITE — FINAL SYSTEM JS */
(function(){'use strict';
const header=document.querySelector('.site-header');let lastY=window.scrollY,ticking=false;
function onScroll(){const y=window.scrollY;if(header){header.classList.toggle('scrolled',y>30);if(y>lastY&&y>90)header.classList.add('nav-hidden');else if(y<lastY)header.classList.remove('nav-hidden')}lastY=y;ticking=false}
window.addEventListener('scroll',()=>{if(!ticking){requestAnimationFrame(onScroll);ticking=true;}},{passive:true});
const mobileMenu=document.querySelector('.mobile-menu'),menuButton=document.querySelector('.menu-btn'),closeButtons=document.querySelectorAll('[data-close-mobile]');
function closeMenu(){if(mobileMenu){mobileMenu.classList.remove('open');mobileMenu.setAttribute('aria-hidden','true')}if(menuButton)menuButton.setAttribute('aria-expanded','false');document.body.classList.remove('menu-open')}
function openMenu(){if(mobileMenu){mobileMenu.classList.add('open');mobileMenu.setAttribute('aria-hidden','false')}if(menuButton)menuButton.setAttribute('aria-expanded','true');document.body.classList.add('menu-open')}
menuButton?.addEventListener('click',()=>mobileMenu?.classList.contains('open')?closeMenu():openMenu());closeButtons.forEach(b=>b.addEventListener('click',closeMenu));document.addEventListener('keydown',e=>{if(e.key==='Escape'){closeMenu();closeSearch()}});
const S=(terms,page,label)=>terms.split('|').map(t=>[t,page,label]);
const SEARCH_DATA=[
...S('real estate|property|properties|buy|sell|invest|plots|land|projects|rent|lease|residential|commercial|bhopal|kolar road|bawadiya kalan|hoshangabad road|ayodhya bypass','real-estate.html','Real Estate'),
...S('travel|holiday|holidays|family|honeymoon|couple|solo|adventure|group|spiritual|hajj|umrah|corporate|business travel|custom travel|maldives|bali|dubai|kashmir|goa|kerala|rajasthan','travel.html','Travel'),
...S('education|admission|course|college|university|mbbs|bds|bams|nursing|engineering|btech|mba|management|aviation|law|design|hospitality|media|science|agriculture|architecture|study abroad|uk|germany|usa|canada|australia|russia|georgia','education.html','Education & Admissions'),
...S('consultancy|business services|business setup|registration|gst|udyam|msme|itr|tax|accounting|legal|documentation|business planning|project report|growth|website|digital|career|recruitment','consultancy.html','Consultancy & Business Services'),
...S('events|wedding|engagement|mehendi|haldi|sangeet|venue|decor|catering|photography|videography|dj|entertainment|birthday|anniversary|corporate event|concert','events.html','Events & Weddings'),
...S('membership|member|privileges|dining|preferred access|travel offers|admission assistance|professional expertise','membership.html','MADHYUM Membership')];
const drawer=document.querySelector('.drawer'),searchInput=document.querySelector('#searchInput'),searchResults=document.querySelector('#searchResults');
function openSearch(){drawer?.classList.add('open');drawer?.setAttribute('aria-hidden','false');setTimeout(()=>searchInput?.focus(),80)}function closeSearch(){drawer?.classList.remove('open');drawer?.setAttribute('aria-hidden','true')}
document.querySelectorAll('[data-search]').forEach(b=>b.addEventListener('click',openSearch));document.querySelectorAll('[data-close-search]').forEach(b=>b.addEventListener('click',closeSearch));drawer?.addEventListener('click',e=>{if(e.target===drawer)closeSearch()});
function esc(s){return s.replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
function renderSearch(q=''){if(!searchResults)return;const raw=q.trim().toLowerCase();if(!raw){searchResults.innerHTML='<div class="result"><strong>Start typing a requirement</strong><small>Try property, Dubai, honeymoon, MBBS, GST, wedding, Hajj, or membership.</small></div>';return}const tokens=raw.split(/\s+/).filter(Boolean),pages={};SEARCH_DATA.forEach(([terms,page,label])=>{const hay=terms.toLowerCase();const hits=tokens.filter(t=>hay.includes(t)).length;if(hits===tokens.length||(tokens.length===1&&hits)){(pages[page]??={label,terms:[]}).terms.push(terms)}});const out=Object.entries(pages);searchResults.innerHTML=out.length?out.map(([page,v])=>`<a class="result" href="${page}"><strong>${esc(v.label)}</strong><small>${esc(v.terms.slice(0,8).join(' • '))}</small></a>`).join(''):'<div class="result"><strong>No matching keyword found</strong><small>Try a broader requirement or service name.</small></div>'}
searchInput?.addEventListener('input',e=>renderSearch(e.target.value));renderSearch();
document.querySelectorAll('a[href^="#"]').forEach(link=>link.addEventListener('click',e=>{const id=link.getAttribute('href');if(!id||id==='#')return;const el=document.querySelector(id);if(!el)return;e.preventDefault();closeMenu();el.scrollIntoView({behavior:'smooth',block:'start'})}));
const reveal=document.querySelectorAll('.reveal');if('IntersectionObserver'in window){const io=new IntersectionObserver(es=>es.forEach(x=>x.isIntersecting&&x.target.classList.add('visible')),{threshold:.08});reveal.forEach(x=>io.observe(x))}else reveal.forEach(x=>x.classList.add('visible'));
const heroOrbit=document.querySelector('.home-page .layered-orbit');if(heroOrbit){const original=[...heroOrbit.querySelectorAll('.layered-wing')];original.forEach(w=>{w.classList.remove('position-left','position-far-left','is-active','position-right','position-far-right');w.removeAttribute('aria-current')});if(!heroOrbit.dataset.tickerReady){original.forEach(w=>{const clone=w.cloneNode(true);clone.setAttribute('aria-hidden','true');clone.setAttribute('tabindex','-1');clone.querySelectorAll('a').forEach(a=>a.setAttribute('tabindex','-1'));heroOrbit.appendChild(clone)});heroOrbit.dataset.tickerReady='true'}}
document.querySelectorAll('.photo-slot[data-photo-slot]').forEach(slot=>{const file=slot.getAttribute('data-photo-slot');if(file)slot.style.backgroundImage=`url(\"${file}\")`});document.querySelectorAll('[data-photo-slot].layered-hero-background').forEach(slot=>{const file=slot.getAttribute('data-photo-slot');if(file)slot.style.backgroundImage=`url(\"${file}\")`});
document.querySelectorAll('.card-photo-slot[data-card-photo]').forEach(slot=>{const file=slot.getAttribute('data-card-photo');if(file)slot.style.backgroundImage=`url(\"${file}\")`});
document.querySelectorAll('.service-more summary').forEach(s=>s.setAttribute('role','button'));
document.querySelectorAll('[data-form-name]').forEach(form=>form.addEventListener('submit',e=>{e.preventDefault();const success=form.querySelector('.form-success');if(success)success.textContent='Thank you. Your requirement has been recorded. Our team will connect with you shortly.';form.reset()}));
})();
